== Data Duplication and Conflict

An organization focused on the delivery of discrete products (such as paper charts, ENCs and nautical publications) may have separate data holdings that contribute to different product lines. This can result in the same data being held more than once (e.g. light information shown on charts being stored in a separate system to the light information in a List of Lights). This is not only inefficient in terms of the volume and use of data held, but can also lead to differences between the data held for the same feature.This has become particularly evident where some ENCs and paper charts have discrepancies between each other and between scales. This puts into question the value of the knowledge portrayed, as the conflict demonstrates doubt and uncertainty in what is correct. Such fragmentation of data, together with proprietary or product specific formats can limit interoperability. This is something that improved data management practices or developing an enterprise SDI within the HO could help to eliminate.
