== Why is MSDI important to a HO?

Involvement in MSDI will elevate the importance of hydrography across a wider marine sector in-country and regionally as well as giving a wider user community exposure to the data and information that can be provided by the HO. It will also provide politicians with the information necessary for government per se, to gain a greater interest and understanding of the role of hydrography nationally.

Hydrography has a vital role in MSDI in providing core "reference" data (such as bathymetry, maritime boundaries, coast line and geographic areas and names). After all, Hydrography is the branch of applied science which deals with the measurement and description of the physical features of oceans, seas, coastal areas, lakes and rivers, as well as with the prediction of their change over time. It does this firstly for the purpose of safety of navigation but also plays a crucial role in the support, through its data and information resources, of all other marine activities, including economic development, security and defense, scientific research, and environmental protection.
