== A look into the Future!

So where will the HOs, as part of the global geospatial community, be in the next 10 years?

There is no doubt that there has never been a more urgent need for a paradigm shift in how we inhabit our planet. Whether we look at it through the lens of climate change, population growth, migration, socio-political unrest, or use of natural resources; it is clear that our current "direction of travel" is unsustainable and potentially unpalatable.

There is no escaping that technology now dominates our lives, with a large part of the world's economy and society now relying on smart phones, IT and the internet. At the heart of today's world is the data that this technology generates. Yet, in these days of big data, open data, the Internet of Things, sensors, augmented reality and almost instantaneous sharing of information on social media, there is a mismatch between the rate of change of technology and the ability for our world's leaders and policy makers to keep up and understand the implications of this change.

The ongoing challenge is that the time taken to deliver such policy and standards is extraordinarily long whilst technology is moving forward much more quickly. In the past, these kinds of technological shifts have allowed humanity to advance its resilience, adaptability and influence.

Spatial information has a critical part to play here as "everything happens somewhere!" Providing a sense of place is extremely powerful because, as humans, we gain comfort from knowing our place and position in the world. This is now more important as our world increasingly operates online and becomes more intangible. But do we believe we as geospatial specialists can fill this role?

There is a widely held belief that the geospatial industry, as we know it, has reached an existential moment. Our past belief in the central role and importance of geospatial data has been eroded by the realization that geo-technology and its use, is now so ubiquitous as to be almost invisible.

Many of the key skillsets we had previously taken for granted as exclusively ours are now shared by other professionals, users and even hobbyists such as gamers, geo-cachers, travelers and ramblers. What this gives the geospatial industry is the opportunity to evolve into a new role in this information rich world.

We must take charge of technology, and not be its slave, by raising our profile to view the wider geospatial picture. There is far more to "location intelligence" than maps and charts. It's all about the data, what you do with it and what outcomes you can provide that counts.

The geospatial industry, of which HOs are part, now has to understand how to switch from being a data provider to becoming a data service and to do it quickly. Data is no longer considered an asset but a 'modus operandi'.

Doing nothing is no longer a realistic option!
